# Generated by Django 3.0.5 on 2020-11-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('loss', models.FloatField()),
                ('val_accuracy', models.FloatField()),
                ('val_loss', models.FloatField()),
                ('filename', models.CharField(max_length=50)),
                ('index', models.IntegerField()),
                ('alogorithm', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiros', models.FileField(blank=True, null=True, upload_to='ficheiros/')),
            ],
        ),
    ]
