# Generated by Django 3.1.3 on 2020-11-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0002_delete_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFiles',
        ),
    ]
